### ISSUE TITLE
KVM entry failure

### ISSUE THREAD

**Issue by bguala** [hermitcore/libhermit#99] opened 2018-08-03 21:02 UTC
Hi!.

This command

$ HERMIT_ISLE=uhyve HERMIT_CPUS=4 HERMIT_MEM=1G HERMIT_VERBOSE=1 bin/proxy x86_64-hermit/extra/benchmarks/stream

generates three errors

KVM: receive shutdown command
proxy: 0:KVM: entry failure: hw_entry_failure_reason=0x80000021
proxy: KVM: unhandled KVM_EXIT_IO / KVM_EXIT_MMIO at port 0x0

**Comment by stlankes** [comment] 2018-08-03 23:26
Hello,

what branch do you use? Do you get any error message from the kernel?

**Comment by bguala** [comment] 2018-08-05 03:01
Hello.

I am using default branch, master. I get these message from the kernel:

[21510.136101] perf interrupt took too long (5026 > 5000), lowering kernel.perf_event_max_sample_rate to 25000

[   12.124842] kvm: VM_EXIT_LOAD_IA32_PERF_GLOBAL_CTRL does not work properly. Using workaround

**Comment by axblk** [comment] 2018-08-05 08:26
Hi!
I am getting the same errors when using more than one core. Interestingly it fails most of the time but not always. I also got the following error a few times:

proxy: KVM: ioctl KVM_SET_SREGS failed: Invalid argument

Actually it seems like there is no mechanism to make sure that the boot cpu has initialized the static sregs variable before the other cpus set their sregs.

**Comment by stlankes** [comment] 2018-08-06 11:38
I never received such kind of failure. Which Linux kernel do you use?

**Comment by bguala** [comment] 2018-08-06 19:03
I am using Linux kernel 3.16.0-4-amd64.

**Comment by stlankes** [comment] 2018-08-12 08:18
@bguala Please test the new version in the master branch. Do you still receive the error?

If you use the Debian packages, please remove all packages and reinstall the packages.

**Comment by bguala** [comment] 2018-08-12 22:56
Stefan,

In this moment, I can't compile the new version of HermitCore. The command **$ make** produces the follow error message:

**Install the project...
-- Install configuration: ""
[ 52%] Completed 'arch_x86_loader'
[ 52%] Built target arch_x86_loader
[ 52%] Built target arch_x86_kernel_asm
[ 52%] Built target libkern
[ 52%] Built target kernel
[ 52%] Built target drivers
[ 52%] Built target mm
[ 52%] Built target lwip
elfedit: Error: Unknown OSABI: Standalone
arch/x86_64/CMakeFiles/kernel-entry.asm.obj.dir/build.make:57: fallo en las instrucciones para el objetivo 'arch/x86_64/CMakeFiles/kernel-entry.asm.obj'
make[2]: *** [arch/x86_64/CMakeFiles/kernel-entry.asm.obj] Error 1
CMakeFiles/Makefile2:806: fallo en las instrucciones para el objetivo 'arch/x86_64/CMakeFiles/kernel-entry.asm.obj.dir/all'
make[1]: *** [arch/x86_64/CMakeFiles/kernel-entry.asm.obj.dir/all] Error 2
Makefile:149: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2**

Previously, I ran **$ sudo apt-get dist-upgrade**, for update Debian packages. Nasm, Make and Binutils are in their most recent version.

**Comment by stlankes** [comment] 2018-08-13 07:38
We changed the value in the elf header (OSABI). For some unknown reasons, a dist-upgrade isn't enough. Please try following commands.

> sudo apt-get remove binutils-hermit newlib-hermit pte-hermit gcc-hermit libomp-hermit libhermit
> sudo apt-get update
> sudo apt-get install binutils-hermit newlib-hermit pte-hermit gcc-hermit libomp-hermit libhermit

**Comment by bguala** [comment] 2018-08-14 02:51
Now, the command **$ cmake ..** generates errors, they are : 

**-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The Fortran compiler identification is unknown
/opt/hermit/libexec/gcc/x86_64-hermit/6.3.0/cc1: error while loading shared libraries: libmpfr.so.6: cannot open shared object file: No such file or directory
-- Check for working C compiler: /opt/hermit/bin/x86_64-hermit-gcc
-- Check for working C compiler: /opt/hermit/bin/x86_64-hermit-gcc -- broken
CMake Error at cmake/cmake-3.7.2-Linux-x86_64/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "/opt/hermit/bin/x86_64-hermit-gcc" is not able to compile a
  simple test program.

  It fails with the following output:

   Change Dir: /home/bguala/Escritorio/Hermit3/libhermit/build/CMakeFiles/CMakeTmp

 Run Build Command:"/usr/bin/make" "cmTC_2bb77/fast"

  /usr/bin/make -f CMakeFiles/cmTC_2bb77.dir/build.make
  CMakeFiles/cmTC_2bb77.dir/build

  make[1]: se entra en el directorio
  '/home/bguala/Escritorio/Hermit3/libhermit/build/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_2bb77.dir/testCCompiler.c.obj

  /opt/hermit/bin/x86_64-hermit-gcc -o
  CMakeFiles/cmTC_2bb77.dir/testCCompiler.c.obj -c
  /home/bguala/Escritorio/Hermit3/libhermit/build/CMakeFiles/CMakeTmp/testCCompiler.c


  /opt/hermit/libexec/gcc/x86_64-hermit/6.3.0/cc1: error while loading shared
  libraries: libmpfr.so.6: cannot open shared object file: No such file or
  directory

  CMakeFiles/cmTC_2bb77.dir/build.make:65: fallo en las instrucciones para el
  objetivo 'CMakeFiles/cmTC_2bb77.dir/testCCompiler.c.obj'

  make[1]: *** [CMakeFiles/cmTC_2bb77.dir/testCCompiler.c.obj] Error 1

  make[1]: se sale del directorio
  '/home/bguala/Escritorio/Hermit3/libhermit/build/CMakeFiles/CMakeTmp'

  Makefile:126: fallo en las instrucciones para el objetivo 'cmTC_2bb77/fast'

  make: *** [cmTC_2bb77/fast] Error 2**

Is **libmpfr** the problem??. I'm not sure, I have **libmpfr4 v3.1.4-1** installed.

I re-installed the follow packages correctly:
binutils-hermit, newlib-hermit, pte-hermit, gcc-hermit, libomp-hermit and libhermit.
Source: **deb http://dl.bintray.com/hermitcore/ubuntu bionic main**.

**Comment by stlankes** [comment] 2018-08-14 19:38
Ubuntu based on Debian, but they use different version of libmpfr. I recognize it on my Debian systems. I want to build "native" Debian packages. But I don't find the time.

Currently, the easiest way to use HermitCore on a Debian system, it the usage of my scripts at https://github.com/hermitcore/hermit-toolchain

It need some time, but it works...

**Comment by bguala** [comment] 2018-08-15 19:49
The command **$ ./toolchain.sh x86_64-hermit /home/bguala/Escritorio/hermit** produces:

Makefile:372: fallo en las instrucciones para el objetivo 'lib_a-fix_grouping.o'
make[4]: *** [lib_a-fix_grouping.o] Error 127
make[4]: *** Se espera a que terminen otras tareas....
Makefile:366: fallo en las instrucciones para el objetivo 'lib_a-locale.o'
make[4]: *** [lib_a-locale.o] Error 127
/bin/bash: x86_64-hermit-cc: no se encontró la orden
Makefile:384: fallo en las instrucciones para el objetivo 'lib_a-lmessages.o'
make[4]: *** [lib_a-lmessages.o] Error 127
/bin/bash: x86_64-hermit-cc: no se encontró la orden
Makefile:378: fallo en las instrucciones para el objetivo 'lib_a-ldpart.o'
make[4]: *** [lib_a-ldpart.o] Error 127
make[4]: se sale del directorio '/home/bguala/.local/share/Trash/files/hermit-toolchain.2/hermit-toolchain/build/tmp/newlib/x86_64-hermit/newlib/libc/locale'
Making all in sys

Makefile:286: fallo en las instrucciones para el objetivo 'lib_a-environ.o'
make[5]: *** [lib_a-environ.o] Error 127
make[5]: *** Se espera a que terminen otras tareas....
/bin/bash: x86_64-hermit-cc: no se encontró la orden
Makefile:292: fallo en las instrucciones para el objetivo 'lib_a-execve.o'
make[5]: *** [lib_a-execve.o] Error 127
/bin/bash: x86_64-hermit-cc: no se encontró la orden
Makefile:274: fallo en las instrucciones para el objetivo 'lib_a-errno.o'
make[5]: *** [lib_a-errno.o] Error 127
/bin/bash: x86_64-hermit-cc: no se encontró la orden
Makefile:280: fallo en las instrucciones para el objetivo 'lib_a-chown.o'
make[5]: *** [lib_a-chown.o] Error 127

/home/bguala/.local/share/Trash/files/hermit-toolchain.2/hermit-toolchain/build
./toolchain.sh: línea 102: cmake: no se encontró la orden
make: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.
make: *** No hay ninguna regla para construir el objetivo 'install'.  Alto.
/home/bguala/.local/share/Trash/files/hermit-toolchain.2/hermit-toolchain/build
./toolchain.sh: línea 111: cmake: no se encontró la orden
make: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.
make: *** No hay ninguna regla para construir el objetivo 'install'.  Alto.

**Comment by bguala** [comment] 2018-08-16 20:46
It doesn't work. The command **$./toolchain x86_64-hermit /home/usr/hermit** produces:

make: *** [all] Error 2
/ home / bguala / Desktop / HermitToolchain / hermit-toolchain / build
./toolchain.sh: line 102: **cmake: order not found**

In toolchain.sh the line 102 is:

cmake -DLIBOMP_ARCH=$TARGET_SHORT -DCMAKE_C_COMPILER=$TARGET-gcc -DCMAKE_CXX_COMPILER=$TARGET-g++ -DCMAKE_INSTALL_PREFIX=$PREFIX/$TARGET -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY -DHERMIT=1 -DLIBOMP_ENABLE_SHARED=OFF -DLIBOMP_FORTRAN_MODULES=OFF -DLIBOMP_OMPT_SUPPORT=OFF -DOPENMP_ENABLE_LIBOMPTARGET=OFF ../../openmp

TARGET is x86_64-hermit.

The build process generates "build" directory in hermit-toolchain. "build" contains hermit (is libhermit), within "hermit" I ran:

> 
> $ . cmake/local-cmake.sh
> $ mkdir build
> $ cd build
> $ cmake ..
>                  -DTOOLCHAIN_DIR_BIN=/home/usr/hermit/bin

but, I get:

The CMAKE_C_COMPILER:
    /home/usr/hermit/bin/x86_64-hermit-gcc -->  is not a full path to an existing compiler tool.

  The CMAKE_CXX_COMPILER:
    /home/usr/hermit/bin/x86_64-hermit-g++ --> is not a full path to an existing compiler tool.

  The CMAKE_Fortran_COMPILER:
    /home/usr/hermit/bin/x86_64-hermit-gfortran --> is not a full path to an existing compiler tool.

  The CMAKE_Go_COMPILER:
    /home/usr/hermit/bin/x86_64-hermit-gccgo --> is not a full path to an existing compiler tool.

What is the full path for compiler tool???./home/usr/hermit/bin???.

**Comment by stlankes** [comment] 2018-08-16 20:50
Hm, which version of cmake do you use?

**Comment by bguala** [comment] 2018-08-16 20:51
cmake 3.7.2

**Comment by stlankes** [comment] 2018-08-16 20:58
I am a little bit confused. I think the the OpenMP library doesn't work on your systems. Please test, if following command is working in the build director of libhermit.

> cmake -DTOOLCHAIN_BIN_DIR=/home/user/hermit/bin -DCMAKE_INSTALL_PREFIX=/home/user/hermit ..
> make

**Comment by stlankes** [comment] 2018-08-16 21:16
I looked in readme of the OpenMP library and found following note

> This repository requires CMake v2.8.0 or later.

That is new for me. We switched to a new OpenMP version and we didn't recognize these changes.

Please download and install cmake from https://cmake.org/files/v3.8/ Afterwards, you should remove the directories `openmp` and `final` from the `build\tmp`directory and start the script again.

**Comment by bguala** [comment] 2018-08-16 21:39
I haven't got any "hermit" directory in /home/bguala.

**Comment by stlankes** [comment] 2018-08-16 21:44
Ok, in this case delete the directory `build\tmp` in the directory of the git repository `hermit-toolchain`. Afterwards, try following commands:

> mkdir /home/bguala/hermit
> ./toolchain x86_64-hermit /home/bguala/hermit
>

**Comment by bguala** [comment] 2018-08-17 02:48
I ran following commands:

> 
> export PATH=/home/bguala/hermit/bin:$PATH
> mkdir /home/bguala/hermit
> ./toolchain x86_64-hermit /home/bguala/hermit

but I get these messages:

> -- Looking for **pthread.h - not found**
> CMake Error at /home/bguala/Escritorio/HermitToolchain/hermit-toolchain/build/hermit/cmake/cmake-3.7.2-Linux-x86_64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
>   **Could NOT find Threads** (missing: Threads_FOUND)
> 
> CMake Error at cmake/cmake-3.7.2-Linux-x86_64/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
>   The C compiler "/home/bguala/hermit/bin/x86_64-hermit-gcc" is not able to
>   compile a simple test program.

Some libomp test failed, for example:
          LIBOMP_HAVE_WNO_SELF_ASSIGN_FLAG
          LIBOMP_HAVE_FINI_FLAG

I haven't got "x_86_64-hermit" directory in /home/bguala/hermit.

**Comment by stlankes** [comment] 2018-08-17 08:48
Ok, at the weekend I will create valid debian packets for you...

**Comment by stlankes** [comment] 2018-08-20 06:25
I try to build packages for Debian "stretch". A few packages are already published at https://bintray.com/hermitcore/debian

However, I am not able to build the final stage of the compiler. You find the log file at https://travis-ci.org/hermitcore/gcc/jobs/418020895

I have no idea why the build process was pending. @jbreitbart Do you have an idea? I don't have any problems on Fedora, CentOS and Ubuntu.

**Comment by jbreitbart** [comment] 2018-08-20 23:04
@stlankes My guess is that travis kills the job if it does not print anything for a 10 minutes and we suppress everything during the built on stdout. On Ubuntu we see warnings being printed on stderr, but Debian does not print any warnings and the job gets killed. I have created

https://github.com/hermitcore/gcc/pull/1

which will fill stdout :smile: If that works fine, we should re-enable bintray for debian and check if there is a more feasible way to get some output on stdout.

**Comment by stlankes** [comment] 2018-08-24 05:44
@bguala It take same time, but the packages are now available. Please use following repository:

> $ echo "deb [trusted=yes] https://dl.bintray.com/hermitcore/debian stretch main" | sudo tee -a /etc/apt/sources.list
> $ sudo apt-get -qq update
> $ sudo apt-get install binutils-hermit newlib-hermit pte-hermit gcc-hermit libomp-hermit libhermit

**Comment by stlankes** [comment] 2018-09-15 14:51
I think that the problem is solved and close the issue. If the problem still exists, please reopen the issue.

**Closed by stlankes** 2018-09-15 14:51 UTC
Labels: bug
